spring:
  application:
    name: spring-boot-backend
#  profiles:
#    active: dev
  datasource:
    url: ${DB_JDBC}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: staging
    show-sql: true
    database-platform: org.hibernate.dialect.postgis.PostgisDialect
management:
  server:
    port: ${ACTUATOR_PORT}
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: ${APP_PORT}
security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: ${JWT_EXPIRATION}
