spring:
  application:
    name: spring-boot-backend
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema:
    database-platform: org.hibernate.dialect.postgis.PostgisDialect